package ii887522.oxy.collection

import ii887522.oxy.functions.toArray
import org.junit.Test
import ii887522.oxy.struct.Pair
import org.junit.Assert.*

class AvlTreeTest {
  @Test fun `test get zero keys`() {
    assertArrayEquals(arrayOf(), AvlTree<Float, String>().keys.toArray())
  }

  @Test fun `test get one key`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    assertArrayEquals(arrayOf(0f), tree.keys.toArray())
  }

  @Test fun `test get 2 keys`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    tree[1f] = "b"
    assertArrayEquals(arrayOf(0f, 1f), tree.keys.toArray())
  }

  @Test fun `test get 3 keys`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    tree[1f] = "b"
    tree[2f] = "c"
    assertArrayEquals(arrayOf(0f, 1f, 2f), tree.keys.toArray())
  }

  @Test fun `test put bulk`() {
    val tree = AvlTree<Float, String>()
    tree.putBulk(
      Pair(0f, "a"),
      Pair(1f, "b"),
      Pair(2f, "c"),
      Pair(3f, "d"),
      Pair(4f, "e"),
      Pair(5f, "f"),
      Pair(6f, "g"),
      Pair(7f, "h"),
      Pair(8f, "i"),
      Pair(9f, "j"),
      Pair(10f, "k"),
      Pair(11f, "l"),
      Pair(12f, "m"),
      Pair(13f, "n"),
      Pair(14f, "o"),
      Pair(15f, "p"),
      Pair(16f, "q"),
      Pair(17f, "r"),
      Pair(18f, "s"),
      Pair(19f, "t"),
      Pair(20f, "u"),
      Pair(21f, "v"),
      Pair(22f, "w"),
      Pair(23f, "x"),
      Pair(24f, "y"),
      Pair(25f, "z"),
      Pair(26f, "aa"),
      Pair(27f, "ab"),
      Pair(28f, "ac"),
      Pair(29f, "ad"),
      Pair(30f, "ae"),
      Pair(31f, "af")
    )
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(32, tree.size)
  }

  @Test fun `test put items in random order to AvlTree`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    assertEquals("a", tree[0f])
    assertEquals(1, tree.size)
    tree[8f] = "b"
    assertEquals("a", tree[0f])
    assertEquals("b", tree[8f])
    assertEquals(2, tree.size)
    tree[16f] = "c"
    assertEquals("a", tree[0f])
    assertEquals("b", tree[8f])
    assertEquals("c", tree[16f])
    assertEquals(3, tree.size)
    tree[-8f] = "d"
    assertEquals("a", tree[0f])
    assertEquals("b", tree[8f])
    assertEquals("c", tree[16f])
    assertEquals("d", tree[-8f])
    assertEquals(4, tree.size)
    tree[0f] = "e"
    assertEquals("e", tree[0f])
    assertEquals("b", tree[8f])
    assertEquals("c", tree[16f])
    assertEquals("d", tree[-8f])
    assertEquals(4, tree.size)
    tree[8f] = "f"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("c", tree[16f])
    assertEquals("d", tree[-8f])
    assertEquals(4, tree.size)
    tree[16f] = "g"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("d", tree[-8f])
    assertEquals(4, tree.size)
    tree[-8f] = "h"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals(4, tree.size)
    tree[-16f] = "i"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals(5, tree.size)
    tree[4f] = "j"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals(6, tree.size)
    tree[24f] = "k"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals(7, tree.size)
    tree[20f] = "l"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals(8, tree.size)
    tree[-12f] = "m"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals(9, tree.size)
    tree[-14f] = "n"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals(10, tree.size)
    tree[-13f] = "o"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals(11, tree.size)
    tree[-10f] = "p"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals(12, tree.size)
    tree[-11f] = "q"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals(13, tree.size)
    tree[-11.5f] = "r"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals(14, tree.size)
    tree[-10.5f] = "s"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals(15, tree.size)
    tree[-11.75f] = "t"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals(16, tree.size)
    tree[-11.625f] = "u"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals(17, tree.size)
    tree[-20f] = "v"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals(18, tree.size)
    tree[-18f] = "w"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals(19, tree.size)
    tree[-13.5f] = "x"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals(20, tree.size)
    tree[-13.25f] = "y"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals(21, tree.size)
    tree[18f] = "z"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals(22, tree.size)
    tree[2f] = "aa"
    tree[6f] = "ab"
    tree[10f] = "ac"
    tree[12f] = "ad"
    tree[14f] = "ae"
    tree[17f] = "af"
    tree[19f] = "ag"
    tree[22f] = "ah"
    tree[26f] = "ai"
    tree[15f] = "aj"
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(32, tree.size)
  }

  @Test fun `test put items in ascending order to AvlTree`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    tree[1f] = "b"
    tree[2f] = "c"
    tree[3f] = "d"
    tree[4f] = "e"
    tree[5f] = "f"
    tree[6f] = "g"
    tree[7f] = "h"
    tree[8f] = "i"
    tree[9f] = "j"
    tree[10f] = "k"
    tree[11f] = "l"
    tree[12f] = "m"
    tree[13f] = "n"
    tree[14f] = "o"
    tree[15f] = "p"
    tree[16f] = "q"
    tree[17f] = "r"
    tree[18f] = "s"
    tree[19f] = "t"
    tree[20f] = "u"
    tree[21f] = "v"
    tree[22f] = "w"
    tree[23f] = "x"
    tree[24f] = "y"
    tree[25f] = "z"
    tree[26f] = "aa"
    tree[27f] = "ab"
    tree[28f] = "ac"
    tree[29f] = "ad"
    tree[30f] = "ae"
    tree[31f] = "af"
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(32, tree.size)
  }

  @Test fun `test put items in descending order to AvlTree`() {
    val tree = AvlTree<Float, String>()
    tree[31f] = "a"
    tree[30f] = "b"
    tree[29f] = "c"
    tree[28f] = "d"
    tree[27f] = "e"
    tree[26f] = "f"
    tree[25f] = "g"
    tree[24f] = "h"
    tree[23f] = "i"
    tree[22f] = "j"
    tree[21f] = "k"
    tree[20f] = "l"
    tree[19f] = "m"
    tree[18f] = "n"
    tree[17f] = "o"
    tree[16f] = "p"
    tree[15f] = "q"
    tree[14f] = "r"
    tree[13f] = "s"
    tree[12f] = "t"
    tree[11f] = "u"
    tree[10f] = "v"
    tree[9f] = "w"
    tree[8f] = "x"
    tree[7f] = "y"
    tree[6f] = "z"
    tree[5f] = "aa"
    tree[4f] = "ab"
    tree[3f] = "ac"
    tree[2f] = "ad"
    tree[1f] = "ae"
    tree[0f] = "af"
    assertEquals("af", tree[0f])
    assertEquals("ae", tree[1f])
    assertEquals("ad", tree[2f])
    assertEquals("ac", tree[3f])
    assertEquals("ab", tree[4f])
    assertEquals("aa", tree[5f])
    assertEquals("z", tree[6f])
    assertEquals("y", tree[7f])
    assertEquals("x", tree[8f])
    assertEquals("w", tree[9f])
    assertEquals("v", tree[10f])
    assertEquals("u", tree[11f])
    assertEquals("t", tree[12f])
    assertEquals("s", tree[13f])
    assertEquals("r", tree[14f])
    assertEquals("q", tree[15f])
    assertEquals("p", tree[16f])
    assertEquals("o", tree[17f])
    assertEquals("n", tree[18f])
    assertEquals("m", tree[19f])
    assertEquals("l", tree[20f])
    assertEquals("k", tree[21f])
    assertEquals("j", tree[22f])
    assertEquals("i", tree[23f])
    assertEquals("h", tree[24f])
    assertEquals("g", tree[25f])
    assertEquals("f", tree[26f])
    assertEquals("e", tree[27f])
    assertEquals("d", tree[28f])
    assertEquals("c", tree[29f])
    assertEquals("b", tree[30f])
    assertEquals("a", tree[31f])
    assertEquals(32, tree.size)
  }

  @Test fun `test min`() {
    val tree = AvlTree<Float, String>()
    assertNull(tree.min())
    assertEquals(0, tree.size)
    tree[2f] = "a"
    assertEquals(Pair(2f, "a"), tree.min())
    assertEquals(1, tree.size)
    tree[1f] = "b"
    assertEquals(Pair(1f, "b"), tree.min())
    assertEquals(2, tree.size)
    tree[0f] = "c"
    assertEquals(Pair(0f, "c"), tree.min())
    assertEquals(3, tree.size)
    tree[3f] = "d"
    assertEquals(Pair(0f, "c"), tree.min())
    assertEquals(4, tree.size)
    tree[4f] = "e"
    assertEquals(Pair(0f, "c"), tree.min())
    assertEquals(5, tree.size)
  }

  @Test fun `test max`() {
    val tree = AvlTree<Float, String>()
    assertNull(tree.max())
    assertEquals(0, tree.size)
    tree[2f] = "a"
    assertEquals(Pair(2f, "a"), tree.max())
    assertEquals(1, tree.size)
    tree[3f] = "b"
    assertEquals(Pair(3f, "b"), tree.max())
    assertEquals(2, tree.size)
    tree[4f] = "c"
    assertEquals(Pair(4f, "c"), tree.max())
    assertEquals(3, tree.size)
    tree[1f] = "d"
    assertEquals(Pair(4f, "c"), tree.max())
    assertEquals(4, tree.size)
    tree[0f] = "e"
    assertEquals(Pair(4f, "c"), tree.max())
    assertEquals(5, tree.size)
  }

  @Test fun `test remove bulk`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    tree[1f] = "b"
    tree[2f] = "c"
    tree[3f] = "d"
    tree[4f] = "e"
    tree[5f] = "f"
    tree[6f] = "g"
    tree[7f] = "h"
    tree[8f] = "i"
    tree[9f] = "j"
    tree[10f] = "k"
    tree[11f] = "l"
    tree[12f] = "m"
    tree[13f] = "n"
    tree[14f] = "o"
    tree[15f] = "p"
    tree[16f] = "q"
    tree[17f] = "r"
    tree[18f] = "s"
    tree[19f] = "t"
    tree[20f] = "u"
    tree[21f] = "v"
    tree[22f] = "w"
    tree[23f] = "x"
    tree[24f] = "y"
    tree[25f] = "z"
    tree[26f] = "aa"
    tree[27f] = "ab"
    tree[28f] = "ac"
    tree[29f] = "ad"
    tree[30f] = "ae"
    tree[31f] = "af"
    tree.removeBulk(
      0f, 1f, 2f, 3f, 4f, 5f, 6f, 7f, 8f, 9f, 10f, 11f, 12f, 13f, 14f, 15f, 16f, 17f, 18f, 19f, 20f, 21f, 22f, 23f, 24f, 25f, 26f, 27f, 28f, 29f, 30f, 31f
    )
    assertNull(tree[0f])
    assertNull(tree[1f])
    assertNull(tree[2f])
    assertNull(tree[3f])
    assertNull(tree[4f])
    assertNull(tree[5f])
    assertNull(tree[6f])
    assertNull(tree[7f])
    assertNull(tree[8f])
    assertNull(tree[9f])
    assertNull(tree[10f])
    assertNull(tree[11f])
    assertNull(tree[12f])
    assertNull(tree[13f])
    assertNull(tree[14f])
    assertNull(tree[15f])
    assertNull(tree[16f])
    assertNull(tree[17f])
    assertNull(tree[18f])
    assertNull(tree[19f])
    assertNull(tree[20f])
    assertNull(tree[21f])
    assertNull(tree[22f])
    assertNull(tree[23f])
    assertNull(tree[24f])
    assertNull(tree[25f])
    assertNull(tree[26f])
    assertNull(tree[27f])
    assertNull(tree[28f])
    assertNull(tree[29f])
    assertNull(tree[30f])
    assertNull(tree[31f])
    assertEquals(0, tree.size)
  }

  @Test fun `test remove items in random order from AvlTree`() {
    val tree = AvlTree<Float, String>()
    assertNull(tree.remove(0f))
    tree[0f] = "e"
    tree[8f] = "f"
    tree[16f] = "g"
    tree[-8f] = "h"
    tree[-16f] = "i"
    tree[4f] = "j"
    tree[24f] = "k"
    tree[20f] = "l"
    tree[-12f] = "m"
    tree[-14f] = "n"
    tree[-13f] = "o"
    tree[-10f] = "p"
    tree[-11f] = "q"
    tree[-11.5f] = "r"
    tree[-10.5f] = "s"
    tree[-11.75f] = "t"
    tree[-11.625f] = "u"
    tree[-20f] = "v"
    tree[-18f] = "w"
    tree[-13.5f] = "x"
    tree[-13.25f] = "y"
    tree[18f] = "z"
    tree[2f] = "aa"
    tree[6f] = "ab"
    tree[10f] = "ac"
    tree[12f] = "ad"
    tree[14f] = "ae"
    tree[17f] = "af"
    tree[19f] = "ag"
    tree[22f] = "ah"
    tree[26f] = "ai"
    tree[15f] = "aj"
    assertNull(tree.remove(1f))
    assertEquals("e", tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(32, tree.size)
    assertEquals("e", tree.remove(0f))
    assertNull(tree[0f])
    assertEquals("f", tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(31, tree.size)
    assertEquals("f", tree.remove(8f))
    assertNull(tree[8f])
    assertEquals("g", tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(30, tree.size)
    assertEquals("g", tree.remove(16f))
    assertNull(tree[16f])
    assertEquals("h", tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(29, tree.size)
    assertEquals("h", tree.remove(-8f))
    assertNull(tree[-8f])
    assertEquals("i", tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(28, tree.size)
    assertEquals("i", tree.remove(-16f))
    assertNull(tree[-16f])
    assertEquals("j", tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(27, tree.size)
    assertEquals("j", tree.remove(4f))
    assertNull(tree[4f])
    assertEquals("k", tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(26, tree.size)
    assertEquals("k", tree.remove(24f))
    assertNull(tree[24f])
    assertEquals("l", tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(25, tree.size)
    assertEquals("l", tree.remove(20f))
    assertNull(tree[20f])
    assertEquals("m", tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(24, tree.size)
    assertEquals("m", tree.remove(-12f))
    assertNull(tree[-12f])
    assertEquals("n", tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(23, tree.size)
    assertEquals("n", tree.remove(-14f))
    assertNull(tree[-14f])
    assertEquals("o", tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(22, tree.size)
    assertEquals("o", tree.remove(-13f))
    assertNull(tree[-13f])
    assertEquals("p", tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(21, tree.size)
    assertEquals("p", tree.remove(-10f))
    assertNull(tree[-10f])
    assertEquals("q", tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(20, tree.size)
    assertEquals("q", tree.remove(-11f))
    assertNull(tree[-11f])
    assertEquals("r", tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(19, tree.size)
    assertEquals("r", tree.remove(-11.5f))
    assertNull(tree[-11.5f])
    assertEquals("s", tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(18, tree.size)
    assertEquals("s", tree.remove(-10.5f))
    assertNull(tree[-10.5f])
    assertEquals("t", tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(17, tree.size)
    assertEquals("t", tree.remove(-11.75f))
    assertNull(tree[-11.75f])
    assertEquals("u", tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(16, tree.size)
    assertEquals("u", tree.remove(-11.625f))
    assertNull(tree[-11.625f])
    assertEquals("v", tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(15, tree.size)
    assertEquals("v", tree.remove(-20f))
    assertNull(tree[-20f])
    assertEquals("w", tree[-18f])
    assertEquals("x", tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(14, tree.size)
    assertEquals("w", tree.remove(-18f))
    assertNull(tree[-18f])
    assertEquals("x",  tree[-13.5f])
    assertEquals("y",  tree[-13.25f])
    assertEquals("z",  tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(13, tree.size)
    assertEquals("x", tree.remove(-13.5f))
    assertNull(tree[-13.5f])
    assertEquals("y", tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(12, tree.size)
    assertEquals("y", tree.remove(-13.25f))
    assertNull(tree[-13.25f])
    assertEquals("z", tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(11, tree.size)
    assertEquals("z", tree.remove(18f))
    assertNull(tree[18f])
    assertEquals("aa", tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(10, tree.size)
    assertEquals("aa", tree.remove(2f))
    assertNull(tree[2f])
    assertEquals("ab", tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(9, tree.size)
    assertEquals("ab", tree.remove(6f))
    assertNull(tree[6f])
    assertEquals("ac", tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(8, tree.size)
    assertEquals("ac", tree.remove(10f))
    assertNull(tree[10f])
    assertEquals("ad", tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(7, tree.size)
    assertEquals("ad", tree.remove(12f))
    assertNull(tree[12f])
    assertEquals("ae", tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(6, tree.size)
    assertEquals("ae", tree.remove(14f))
    assertNull(tree[14f])
    assertEquals("af", tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(5, tree.size)
    assertEquals("af", tree.remove(17f))
    assertNull(tree[17f])
    assertEquals("ag", tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(4, tree.size)
    assertEquals("ag", tree.remove(19f))
    assertNull(tree[19f])
    assertEquals("ah", tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(3, tree.size)
    assertEquals("ah", tree.remove(22f))
    assertNull(tree[22f])
    assertEquals("ai", tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(2, tree.size)
    assertEquals("ai", tree.remove(26f))
    assertNull(tree[26f])
    assertEquals("aj", tree[15f])
    assertEquals(1, tree.size)
    assertEquals("aj", tree.remove(15f))
    assertNull(tree[15f])
    assertEquals(0, tree.size)
  }

  @Test fun `test remove items in ascending order from AvlTree`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    tree[1f] = "b"
    tree[2f] = "c"
    tree[3f] = "d"
    tree[4f] = "e"
    tree[5f] = "f"
    tree[6f] = "g"
    tree[7f] = "h"
    tree[8f] = "i"
    tree[9f] = "j"
    tree[10f] = "k"
    tree[11f] = "l"
    tree[12f] = "m"
    tree[13f] = "n"
    tree[14f] = "o"
    tree[15f] = "p"
    tree[16f] = "q"
    tree[17f] = "r"
    tree[18f] = "s"
    tree[19f] = "t"
    tree[20f] = "u"
    tree[21f] = "v"
    tree[22f] = "w"
    tree[23f] = "x"
    tree[24f] = "y"
    tree[25f] = "z"
    tree[26f] = "aa"
    tree[27f] = "ab"
    tree[28f] = "ac"
    tree[29f] = "ad"
    tree[30f] = "ae"
    tree[31f] = "af"
    assertEquals("a", tree.remove(0f))
    assertNull(tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(31, tree.size)
    assertEquals("b", tree.remove(1f))
    assertNull(tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(30, tree.size)
    assertEquals("c", tree.remove(2f))
    assertNull(tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(29, tree.size)
    assertEquals("d", tree.remove(3f))
    assertNull(tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(28, tree.size)
    assertEquals("e", tree.remove(4f))
    assertNull(tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(27, tree.size)
    assertEquals("f", tree.remove(5f))
    assertNull(tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(26, tree.size)
    assertEquals("g", tree.remove(6f))
    assertNull(tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(25, tree.size)
    assertEquals("h", tree.remove(7f))
    assertNull(tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(24, tree.size)
    assertEquals("i", tree.remove(8f))
    assertNull(tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(23, tree.size)
    assertEquals("j", tree.remove(9f))
    assertNull(tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(22, tree.size)
    assertEquals("k", tree.remove(10f))
    assertNull(tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(21, tree.size)
    assertEquals("l", tree.remove(11f))
    assertNull(tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(20, tree.size)
    assertEquals("m", tree.remove(12f))
    assertNull(tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(19, tree.size)
    assertEquals("n", tree.remove(13f))
    assertNull(tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(18, tree.size)
    assertEquals("o", tree.remove(14f))
    assertNull(tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(17, tree.size)
    assertEquals("p", tree.remove(15f))
    assertNull(tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(16, tree.size)
    assertEquals("q", tree.remove(16f))
    assertNull(tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(15, tree.size)
    assertEquals("r", tree.remove(17f))
    assertNull(tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(14, tree.size)
    assertEquals("s", tree.remove(18f))
    assertNull(tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(13, tree.size)
    assertEquals("t", tree.remove(19f))
    assertNull(tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(12, tree.size)
    assertEquals("u", tree.remove(20f))
    assertNull(tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(11, tree.size)
    assertEquals("v", tree.remove(21f))
    assertNull(tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(10, tree.size)
    assertEquals("w", tree.remove(22f))
    assertNull(tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(9, tree.size)
    assertEquals("x", tree.remove(23f))
    assertNull(tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(8, tree.size)
    assertEquals("y", tree.remove(24f))
    assertNull(tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(7, tree.size)
    assertEquals("z", tree.remove(25f))
    assertNull(tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(6, tree.size)
    assertEquals("aa", tree.remove(26f))
    assertNull(tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(5, tree.size)
    assertEquals("ab", tree.remove(27f))
    assertNull(tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(4, tree.size)
    assertEquals("ac", tree.remove(28f))
    assertNull(tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(3, tree.size)
    assertEquals("ad", tree.remove(29f))
    assertNull(tree[29f])
    assertEquals("ae", tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(2, tree.size)
    assertEquals("ae", tree.remove(30f))
    assertNull(tree[30f])
    assertEquals("af", tree[31f])
    assertEquals(1, tree.size)
    assertEquals("af", tree.remove(31f))
    assertNull(tree[31f])
    assertEquals(0, tree.size)
  }

  @Test fun `test remove items in descending order from AvlTree`() {
    val tree = AvlTree<Float, String>()
    tree[0f] = "a"
    tree[1f] = "b"
    tree[2f] = "c"
    tree[3f] = "d"
    tree[4f] = "e"
    tree[5f] = "f"
    tree[6f] = "g"
    tree[7f] = "h"
    tree[8f] = "i"
    tree[9f] = "j"
    tree[10f] = "k"
    tree[11f] = "l"
    tree[12f] = "m"
    tree[13f] = "n"
    tree[14f] = "o"
    tree[15f] = "p"
    tree[16f] = "q"
    tree[17f] = "r"
    tree[18f] = "s"
    tree[19f] = "t"
    tree[20f] = "u"
    tree[21f] = "v"
    tree[22f] = "w"
    tree[23f] = "x"
    tree[24f] = "y"
    tree[25f] = "z"
    tree[26f] = "aa"
    tree[27f] = "ab"
    tree[28f] = "ac"
    tree[29f] = "ad"
    tree[30f] = "ae"
    tree[31f] = "af"
    assertEquals("af", tree.remove(31f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertEquals("ae", tree[30f])
    assertNull(tree[31f])
    assertEquals(31, tree.size)
    assertEquals("ae", tree.remove(30f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertEquals("ad", tree[29f])
    assertNull(tree[30f])
    assertEquals(30, tree.size)
    assertEquals("ad", tree.remove(29f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertEquals("ac", tree[28f])
    assertNull(tree[29f])
    assertEquals(29, tree.size)
    assertEquals("ac", tree.remove(28f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertEquals("ab", tree[27f])
    assertNull(tree[28f])
    assertEquals(28, tree.size)
    assertEquals("ab", tree.remove(27f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertEquals("aa", tree[26f])
    assertNull(tree[27f])
    assertEquals(27, tree.size)
    assertEquals("aa", tree.remove(26f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertEquals("z", tree[25f])
    assertNull(tree[26f])
    assertEquals(26, tree.size)
    assertEquals("z", tree.remove(25f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertEquals("y", tree[24f])
    assertNull(tree[25f])
    assertEquals(25, tree.size)
    assertEquals("y", tree.remove(24f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertEquals("x", tree[23f])
    assertNull(tree[24f])
    assertEquals(24, tree.size)
    assertEquals("x", tree.remove(23f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertEquals("w", tree[22f])
    assertNull(tree[23f])
    assertEquals(23, tree.size)
    assertEquals("w", tree.remove(22f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertEquals("v", tree[21f])
    assertNull(tree[22f])
    assertEquals(22, tree.size)
    assertEquals("v", tree.remove(21f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertEquals("u", tree[20f])
    assertNull(tree[21f])
    assertEquals(21, tree.size)
    assertEquals("u", tree.remove(20f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertEquals("t", tree[19f])
    assertNull(tree[20f])
    assertEquals(20, tree.size)
    assertEquals("t", tree.remove(19f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertEquals("s", tree[18f])
    assertNull(tree[19f])
    assertEquals(19, tree.size)
    assertEquals("s", tree.remove(18f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertEquals("r", tree[17f])
    assertNull(tree[18f])
    assertEquals(18, tree.size)
    assertEquals("r", tree.remove(17f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertEquals("q", tree[16f])
    assertNull(tree[17f])
    assertEquals(17, tree.size)
    assertEquals("q", tree.remove(16f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertEquals("p", tree[15f])
    assertNull(tree[16f])
    assertEquals(16, tree.size)
    assertEquals("p", tree.remove(15f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertEquals("o", tree[14f])
    assertNull(tree[15f])
    assertEquals(15, tree.size)
    assertEquals("o", tree.remove(14f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertEquals("n", tree[13f])
    assertNull(tree[14f])
    assertEquals(14, tree.size)
    assertEquals("n", tree.remove(13f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertEquals("m", tree[12f])
    assertNull(tree[13f])
    assertEquals(13, tree.size)
    assertEquals("m", tree.remove(12f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertEquals("l", tree[11f])
    assertNull(tree[12f])
    assertEquals(12, tree.size)
    assertEquals("l", tree.remove(11f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertEquals("k", tree[10f])
    assertNull(tree[11f])
    assertEquals(11, tree.size)
    assertEquals("k", tree.remove(10f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertEquals("j", tree[9f])
    assertNull(tree[10f])
    assertEquals(10, tree.size)
    assertEquals("j", tree.remove(9f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertEquals("i", tree[8f])
    assertNull(tree[9f])
    assertEquals(9, tree.size)
    assertEquals("i", tree.remove(8f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertEquals("h", tree[7f])
    assertNull(tree[8f])
    assertEquals(8, tree.size)
    assertEquals("h", tree.remove(7f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertEquals("g", tree[6f])
    assertNull(tree[7f])
    assertEquals(7, tree.size)
    assertEquals("g", tree.remove(6f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertEquals("f", tree[5f])
    assertNull(tree[6f])
    assertEquals(6, tree.size)
    assertEquals("f", tree.remove(5f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertEquals("e", tree[4f])
    assertNull(tree[5f])
    assertEquals(5, tree.size)
    assertEquals("e", tree.remove(4f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertEquals("d", tree[3f])
    assertNull(tree[4f])
    assertEquals(4, tree.size)
    assertEquals("d", tree.remove(3f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertEquals("c", tree[2f])
    assertNull(tree[3f])
    assertEquals(3, tree.size)
    assertEquals("c", tree.remove(2f))
    assertEquals("a", tree[0f])
    assertEquals("b", tree[1f])
    assertNull(tree[2f])
    assertEquals(2, tree.size)
    assertEquals("b",tree.remove(1f))
    assertEquals("a", tree[0f])
    assertNull(tree[1f])
    assertEquals(1, tree.size)
    assertEquals("a", tree.remove(0f))
    assertNull(tree[0f])
    assertEquals(0, tree.size)
  }

  @Test fun `test to array preorder`() {
    val tree = AvlTree<Int, String>()
    assertArrayEquals(arrayOf(), tree.toArrayPreorder())
    tree[1] = "a"
    assertArrayEquals(arrayOf(Pair(1, "a")), tree.toArrayPreorder())
    tree[0] = "b"
    assertArrayEquals(arrayOf(Pair(1, "a"), Pair(0, "b")), tree.toArrayPreorder())
    tree[2] = "c"
    assertArrayEquals(arrayOf(Pair(1, "a"), Pair(0, "b"), Pair(2, "c")), tree.toArrayPreorder())
    tree[3] = "d"
    assertArrayEquals(arrayOf(Pair(1, "a"), Pair(0, "b"), Pair(2, "c"), Pair(3, "d")), tree.toArrayPreorder())
    tree[4] = "e"
    assertArrayEquals(arrayOf(Pair(1, "a"), Pair(0, "b"), Pair(3, "d"), Pair(2, "c"), Pair(4, "e")), tree.toArrayPreorder())
  }

  @Test fun `test to array inorder`() {
    val tree = AvlTree<Float, String>()
    assertArrayEquals(arrayOf(), tree.toArrayInorder())
    tree[1f] = "a"
    assertArrayEquals(arrayOf(Pair(1f, "a")), tree.toArrayInorder())
    tree[0f] = "b"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(1f, "a")), tree.toArrayInorder())
    tree[2f] = "c"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(1f, "a"), Pair(2f, "c")), tree.toArrayInorder())
    tree[3f] = "d"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(1f, "a"), Pair(2f, "c"), Pair(3f, "d")), tree.toArrayInorder())
    tree[4f] = "e"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(1f, "a"), Pair(2f, "c"), Pair(3f, "d"), Pair(4f, "e")), tree.toArrayInorder())
  }

  @Test fun `test to array postorder`() {
    val tree = AvlTree<Float, String>()
    assertArrayEquals(arrayOf(), tree.toArrayPostorder())
    tree[1f] = "a"
    assertArrayEquals(arrayOf(Pair(1f, "a")), tree.toArrayPostorder())
    tree[0f] = "b"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(1f, "a")), tree.toArrayPostorder())
    tree[2f] = "c"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(2f, "c"), Pair(1f, "a")), tree.toArrayPostorder())
    tree[3f] = "d"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(3f, "d"), Pair(2f, "c"), Pair(1f, "a")), tree.toArrayPostorder())
    tree[4f] = "e"
    assertArrayEquals(arrayOf(Pair(0f, "b"), Pair(2f, "c"), Pair(4f, "e"), Pair(3f, "d"), Pair(1f, "a")), tree.toArrayPostorder())
  }

  @Test fun `test clear`() {
    val tree = AvlTree<Float, String>()
    tree.clear()
    assertEquals(0, tree.size)
    tree[1f] = "a"
    tree.clear()
    assertEquals(0, tree.size)
  }
}
